- install/os-x.md
Because sandbox issue solving way is found.
ref: https://github.com/Homebrew/homebrew/pull/45611
> doc osx: Follow pgroonga formula change

- tutorial/index.md
Replaced operators from `%%` `@@` with `&@` `&?` `` &` `` because `%%` and `@@` are deprecated from version 1.2.1.
> tutorial/index.md: replaced operators

- _includes/navbar-content.en.html
- faq/index.md
- index.md
- install/source.md
Create a FAQ section and document how to build a SELinux policy package. [Related issue](https://github.com/pgroonga/pgroonga/issues/91). 
Perhaps I made some mistakes since I'm not familiar with the documentation builder. Also, these changes are only for the English section. I would be nice if someone that knows Japanese could translate them.
> Add SELinux instructions and FAQ

- reference/pgroonga-versus-gist-and-gin.md
Fixed a typo and changed the wording of comparisons because "more faster/more larger" is grammatically wrong.
> reference: fixed a typo and changed the wording of comparisons

- tutorial/index.md
Fixed broken links for `Regular expression` and `Similar search` sections on [tutorial page](https://pgroonga.github.io/tutorial/#regular-expression).
Extra whitespaces are removed by IDE. If it's critical I can revert them.
> fix: broken reference links

- reference/index.md
`CREATE INDEX USING pgroonga`の解説は素晴らしいけれど、ドキュメント上のこの赤色はリンクだったり、リンクでなかったりしてクリックできると気付きにくいので、より分かりやすく修正
また、PGroongaインデックス作成時のさまざまなノウハウが詰まったページである感を `in detail` で演出
> Make code only link more noticeable

- reference/modules/pgroonga-standby-maintainer.md
https://github.com/pgroonga/pgroonga.github.io/pull/100 より
`pgroonga_wal_applier`はdeprecatedとなり`pgroonga_standby_maintainer`がメインとなったので、本ドキュメント記載の
> This is still an experimental feature.
は紛らわしいため削除
> pgroonga_standby_maintainer: mark stable

- reference/operators/query-v2.md
NOT検索が使えるのに例に載ってないのも勿体無いと思って追加しました
でもGroongaのクエリー構文にはNOT検索が見当たらない
PGroonga独自？
> query-v2: Add NOT search in Summary example

- reference/functions/pgroonga-normalize.md
自分がノーマライザーのオプションの複数指定時に`'`の付け方がよく分からなくてエラーで悩んでいたので、同じような問題に悩む人が出ないように事例を追加
> pgroonga_normalize: add one more example to specify multiple normalizers

- faq/index.md
Add PGroonga on the managed service
Add Trouble Shooting
> faq: add managed PGroonga

- how-to/laravel.md
I just happened to find a typo.
> Fix a typo in Laravel tutorial

- users/index.md
当館の利用事例について国立国会図書館の情報ポータルで紹介されておりましたので、PGroongaさんのサイトでも紹介いただけると幸いです
> Add use case of National Institute of Japanese Literature

- reference/create-index-using-pgroonga.md
- reference/functions/pgroonga-highlight-html.md
This will add missing `NormalizerTable` parameter that required when using `pgroonga_highlight_html` with `NormalizerTable`.
> Add missing parameter option for `pgroonga_highlight_html` when using with `NormalizerTable`

- uninstall/index.md
> fix: uninstall/index.md typo

- install/macos.md
- ja/install/macos.md
GitHub: fix GH-318
MeCab is always enabled in the `groonga` formula.
> install macos: Remove needless MeCab related description

- _po/ja/reference/operators/similar-search-v2.po
- _po/ja/v1/reference/operators/similar-search-v2.po
- ja/reference/operators/similar-search-v2.md
- ja/v1/reference/operators/similar-search-v2.md
- I fix some translations of the similar search function about varchar type.
- ref: v1: https://github.com/pgroonga/pgroonga/blob/3d3277c9e297d1a9e0c681b9edf15be8343035f4/data/pgroonga--1.2.1--1.2.2.sql#L70-L74
- ref: v2: https://github.com/pgroonga/pgroonga/blob/3d3277c9e297d1a9e0c681b9edf15be8343035f4/data/pgroonga.sql#L1206-L1212
> reference similar-search-v2: fix translations

- development/build.md
* Install postgres_fdw module
* https://github.com/pgroonga/pgroonga/discussions/406#discussioncomment-8536777
* Add parameter to initdb
* https://github.com/pgroonga/pgroonga/discussions/406#discussioncomment-8537005
* The `max_prepared_transactions=1` is not noted in the discussions, though, without this parameter, the test `sql/vacuum/two-phase-commit.sql` fails.
> Add to development/build for successful testing

- _po/ja/reference/functions/pgroonga-list-lagged-indexes.po
- ja/reference/functions/pgroonga-list-lagged-indexes.md
Match the translation set in the other `po`.
> Remove unnecessary space

- _po/ja/troubleshooting/index.po
- ja/troubleshooting/index.md
- troubleshooting/index.md
This PR fixed the details summary layout because the kramdown's
parser regards the summary as a block and generates unexpected
HTML layout like the following.
So we explicitly specified the summary is a inline block to solve
it. After https://github.com/gettalong/kramdown/pull/819 is solved,
we can just add the `parse-block-html` option to handle it.
|Before|After|
|---|---|
| ![Screenshot from 2024-12-12 09-09-21](https://github.com/user-attachments/assets/771496ad-1de4-4eb0-8d05-3d224f5a9f58) | ![Screenshot from 2024-12-12 09-10-01](https://github.com/user-attachments/assets/3d97b8d6-5fb9-4567-b223-6c18eb070a83) |
FYI: This PR doesn't add additional css to fix the layout of details and summary.
> troubleshooting: fix details summary layout

- reference/create-index-using-pgroonga.md
BigramBigram part is duplicated typo.
> Fix Tokenizer name Typo
