pgroonga/pgroonga.github.io

news/index.md
```log
vre ions ->
versions
^^+
```
=> Fix a typo in news

ja/reference/index.md, ja/reference/parameters/lock_timeout.md, ja/reference/parameters/log_level.md, ja/reference/parameters/log_path.md, ja/reference/parameters/log_type.md, reference/index.md, reference/parameters/lock_timeout.md, reference/parameters/log_level.md, reference/parameters/log_path.md, reference/parameters/log_type.md
Copy parameter doc from Release notes.
=> [WIP] Update document

install/source.md, ja/install/source.md
Need xxhash.h and xxhash.c
```
git clone https://github.com/pgroonga/pgroonga.git
cd pgroonga
make
```
```
pgroonga.c:155:20: fatal error: xxhash.h: No such file or directory
#include <xxhash.h>
^
compilation terminated.
make: *** [pgroonga.o] Error 1
```
=> Add --recursive option

reference/index.md
Follow up [Need Tuning link. #6](https://github.com/pgroonga/pgroonga/issues/6)
=> Add tuning link

upgrade/index.md
PGroonga 1.0.1 and 1.0.0 are compatible versions.
=> Add a compatible versions list element

ja/tutorial/index.md, tutorial/index.md
* Fix a typo in Japanese version
* Use `LIKE` operator in `LIKE` operator section
=> Fix tutorial

_config.yml, _po/ja/news/index.po, ja/news/index.md, news/index.md
I'll add po file later. I've forgot how to generate po file.
(Or please add missing documents).
=> Add 1.0.4 and 1.0.5 entry

reference/operators/query.md
Added definition `[query-v2]:query-v2.html` (link) in query.md
=> Added definition `[query-v2]:query-v2.html` (link)

reference/operators/script-jsonb-v2.md
* old title: `` &`` `` operator for `jsonb` type
* new title: `` &` `` operator for `jsonb` type
=> script-jsonb-v2.md : Fixed title

install/freebsd.md
I have ported pgroonga in FreeBSD. 
http://www.freshports.org/databases/pgroonga/
=> Update as pgroonga has been ported to FreeBSD

_po/ja/reference/create-index-using-pgroonga.po, _po/ja/v1/reference/create-index-using-pgroonga.po, reference/create-index-using-pgroonga.md, v1/reference/create-index-using-pgroonga.md
Custom is not verb but adjective.
I replaced "custom" with its verb form.
=> Use verb form for "custom"

users/index.md
日本語ですが記載させていただきました。
よろしくお願いします！
=> add service waja.

_po/ja/how-to/auto-complete.po, how-to/auto-complete.md, ja/how-to/auto-complete.md
=> doc: remove prefix search

reference/functions/pgroonga-highlight-html.md
If you are not familiar with SQL or PGroonga, you might have some tough times to implement pgroonga_highlight_html to your application. Hopefully this example solve that experience.
=> Added pgroonga_highlight_html Example

tutorial/index.md
added pgroonga_highlight_html example.
=> tutorial: add pgroonga_highlight_html

_po/ja/tutorial/index.po, ja/tutorial/index.md, tutorial/index.md
チュートリアルをそのまま実行したらエラーで怒られたので`CREATE EXTENSION pgroonga;`を追記
=> Add CREATE EXTENSION before creating index

reference/create-index-using-pgroonga.md
- 各項目が分かりやすくなるように箇条書きリンクを追加
- NormalizerTableセクション追加
=> Add Table of Contents Links and NormalizerTable section

reference/create-index-using-pgroonga.md
=> Recommend Tokenizers for alphabet language

assets/stylesheets/pgroonga.scss, how-to/laravel.md
Actual document screenshot size is just too big...
We need to add width to `<img>` tag for better presentation.
=> tutorial laravel: set max width to avoid large image display

reference/operators/query-v2.md
This fix will prevent people from getting confused. https://github.com/groonga/groonga/discussions/1591
=> Fix a typo

how-to/postgrest.md
- NOT search function added
- Google-Like Search feature added
=> Add More Practical Features

how-to/postgrest.md
=> Update description to match new example

_po/ja/install/almalinux.po, _po/ja/install/centos.po, _po/ja/install/debian.po, _po/ja/install/freebsd.po, _po/ja/install/macos.po, _po/ja/install/source.po, _po/ja/install/ubuntu.po, _po/ja/install/windows.po, ja/install/almalinux.md, ja/install/centos.md, ja/install/debian.md, ja/install/freebsd.md, ja/install/macos.md, ja/install/source.md, ja/install/ubuntu.md, ja/install/windows.md
- Fix the translations on install page
| Before | After |
|---|---|
|![before](https://github.com/pgroonga/pgroonga.github.io/assets/45173523/03560771-5407-4a2d-ad2c-0bda3608b9eb)| ![after](https://github.com/pgroonga/pgroonga.github.io/assets/45173523/d1d15a0b-fa1b-45cf-8c43-05e0d1d4f65f) |
=> install: fix translations

ja/reference/parameters/pgroonga-crash-safer-max-recovery-threads.md
I ran `rake` and found the diff, so I commit it.
=> Update auto-generated file

_po/ja/development/release.po, _po/ja/development/release.pot, development/release.md, ja/development/release.md
This is an operation that is now unnecessary.
=> Remove unnecessary contents from the release document

_po/ja/development/release.po, _po/ja/development/release.pot, development/release.md, ja/development/release.md
* Debian -> deb
* CentOS -> RPM
=> Change the name of package type

ja/reference/index.md
`ja/reference/index.md` update was missed.
GH-346
=> Update ja reference index

_po/ja/reference/functions/pgroonga-list-broken-indexes.po, _po/ja/reference/functions/pgroonga-list-broken-indexes.pot, _po/ja/reference/functions/pgroonga-list-lagged-indexes.po, _po/ja/reference/functions/pgroonga-list-lagged-indexes.pot, ja/reference/functions/pgroonga-list-broken-indexes.md, ja/reference/functions/pgroonga-list-lagged-indexes.md, reference/functions/pgroonga-list-broken-indexes.md, reference/functions/pgroonga-list-lagged-indexes.md
=> Add implemented version

_po/ja/install/source.po, install/source.md, ja/install/source.md
no "-" between "pkg" and "config".
=> install: fix wrong PKG_CONFIG_PATH

_po/ja/reference/parameters/log-type.po, ja/reference/parameters/log-type.md, reference/parameters/log-type.md
https://github.com/pgroonga/pgroonga/issues/539
=> parameters/log-type: Add a note about default values since there was no reference to them

_po/ja/reference/functions/pgroonga-condition.po, _po/ja/reference/operators/match-jsonb-v2.po, _po/ja/reference/operators/match-v2.po, _po/ja/reference/operators/query-v2.po, _po/ja/reference/parameters/enable-row-level-security.po, _po/ja/v1/reference/operators/match-jsonb-v2.po, ja/reference/functions/pgroonga-condition.md, ja/reference/operators/match-jsonb-v2.md, ja/reference/operators/match-v2.md, ja/reference/operators/query-v2.md, ja/reference/parameters/enable-row-level-security.md, ja/v1/reference/operators/match-jsonb-v2.md
Since there were multiple patterns of Japanese translations of the same English sentence, we will unify them.
=> Unify Japanese translations

users/index.md
=> Add Kelteu use case

ja/how-to/tuning.md
=> Update ja/how-to/tuning.md, run `rake` command
